# fly.toml app configuration file generated for gearbot on 2026-01-09T01:32:04-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gearbot'
primary_region = 'lax'

[build]
  builder = 'paketobuildpacks/builder:base'

[processes]
  worker = 'python bot.py'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
